package main.menuitems;
import main.DatabaseConnection;
import main.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Class that creates the exit menu item.
 * @author Elena Roncolino
 */
public class ExitMenuItem extends JMenuItem {

    /**
     * Method that builds the exit menu item.
     * @return JMenuItem The exit menu item.
     */
    public JMenuItem buildExitMenuItem() {
        ImageIcon exitImage = new ImageIcon(new ImageIcon("images/exit.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        JMenuItem exitMenu = new JMenuItem("Exit", exitImage);
        exitMenu.addActionListener(new ActionListener() {
            /**
             * Method that overrides the default one and asks the user if he is sure he wants to quit the application.
             * If yes, the application is shut down.
             * @param e The event generated by pressing the exit menu item.
             */
            public void actionPerformed(ActionEvent e) {
                int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to close the application?",
                        "Quit application", JOptionPane.YES_NO_CANCEL_OPTION);

                if (result == JOptionPane.YES_OPTION){
                    DatabaseConnection.getInstance().closeConnection();
                    System.exit(0);
                }
            }
        });

        return exitMenu;
    }
}